### PR TITLE
👌 IMPROVE: Fix PHP linting warnings (#1473)

### LINKED ISSUE #1473: Fix PHP linting warnings
Running `npm run lint:php` does not fully run currently and will be exited earlier with the following log:

```
> storefront@2.6.0 lint:php /Users/nielslange/Development/themes/storefront
> composer run-script phpcs ./

> phpcs --extensions=php -s -p './'
.......WW.......WW.W.W.................. 40 / 40 (100%)



FILE: ...emes/storefront/inc/woocommerce/class-storefront-woocommerce.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 3 WARNINGS AFFECTING 3 LINES
----------------------------------------------------------------------
 414 | WARNING | Found precision alignment of 1 spaces.
     |         | (WordPress.WhiteSpace.PrecisionAlignment.Found)
 415 | WARNING | Found precision alignment of 1 spaces.
     |         | (WordPress.WhiteSpace.PrecisionAlignment.Found)
 416 | WARNING | Found precision alignment of 1 spaces.
     |         | (WordPress.WhiteSpace.PrecisionAlignment.Found)
----------------------------------------------------------------------


FILE: ...c/woocommerce/class-storefront-woocommerce-adjacent-products.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 86 | WARNING | Variable assignment found within a condition. Did you
    |         | mean to do a comparison?
    |         | (WordPress.CodeAnalysis.AssignmentInCondition.FoundInWhileCondition)
----------------------------------------------------------------------


FILE: .../themes/storefront/inc/admin/class-storefront-plugin-install.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 126 | WARNING | Method name "_is_plugin_installed" should not be
     |         | prefixed with an underscore to indicate
     |         | visibility
     |         | (PSR2.Methods.MethodDeclaration.Underscore)
----------------------------------------------------------------------


FILE: ...velopment/themes/storefront/inc/admin/class-storefront-admin.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 217 | WARNING | Method name "_is_plugin_installed" should not be
     |         | prefixed with an underscore to indicate
     |         | visibility
     |         | (PSR2.Methods.MethodDeclaration.Underscore)
----------------------------------------------------------------------


FILE: ...emes/storefront/inc/nux/class-storefront-nux-starter-content.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 18 WARNINGS AFFECTING 15 LINES
----------------------------------------------------------------------
   42 | WARNING | Processing form data without nonce
      |         | verification.
      |         | (WordPress.Security.NonceVerification.Recommended)
   42 | WARNING | Processing form data without nonce
      |         | verification.
      |         | (WordPress.Security.NonceVerification.Recommended)
  206 | WARNING | Found precision alignment of 3 spaces.
      |         | (WordPress.WhiteSpace.PrecisionAlignment.Found)
  272 | WARNING | Processing form data without nonce
      |         | verification.
      |         | (WordPress.Security.NonceVerification.Recommended)
  272 | WARNING | Processing form data without nonce
      |         | verification.
      |         | (WordPress.Security.NonceVerification.Recommended)
  286 | WARNING | Processing form data without nonce
      |         | verification.
      |         | (WordPress.Security.NonceVerification.Recommended)
  286 | WARNING | Processing form data without nonce
      |         | verification.
      |         | (WordPress.Security.NonceVerification.Recommended)
  287 | WARNING | Processing form data without nonce
      |         | verification.
      |         | (WordPress.Security.NonceVerification.Recommended)
  659 | WARNING | Passing the $glue and $pieces parameters in reverse
      |         | order to implode has been deprecated since PHP 7.4;
      |         | $glue should be the first parameter and $pieces the
      |         | second
      |         | (PHPCompatibility.ParameterValues.RemovedImplodeFlScript phpcs --extensions=php -s -p handling the phpcs event returned with error code 1
exibleParamOrder.Deprecated)
  724 | WARNING | Method name "_starter_content_products" should not
      |         | be prefixed with an underscore to indicate
      |         | visibility
      |         | (PSR2.Methods.MethodDeclaration.Underscore)
 1037 | WARNING | Method name "_homepage_blocks_content" should not
      |         | be prefixed with an underscore to indicate
      |         | visibility
      |         | (PSR2.Methods.MethodDeclaration.Underscore)
 1085 | WARNING | Method name "_replace_homepage_blocks_symbols"
      |         | should not be prefixed with an underscore to
      |         | indicate visibility
      |         | (PSR2.Methods.MethodDeclaration.Underscore)
 1150 | WARNING | Method name "_get_created_starter_content_products"
      |         | should not be prefixed with an underscore to
      |         | indicate visibility
      |         | (PSR2.Methods.MethodDeclaration.Underscore)
 1172 | WARNING | Method name "_get_existing_wc_products" should not
      |         | be prefixed with an underscore to indicate
      |         | visibility
      |         | (PSR2.Methods.MethodDeclaration.Underscore)
 1198 | WARNING | Method name "_query_starter_content" should not be
      |         | prefixed with an underscore to indicate
      |         | visibility
      |         | (PSR2.Methods.MethodDeclaration.Underscore)
 1203 | WARNING | Detected usage of meta_query, possible slow
      |         | query.
      |         | (WordPress.DB.SlowDBQuery.slow_db_query_meta_query)
 1238 | WARNING | Method name "_get_category_image_attachment_id"
      |         | should not be prefixed with an underscore to
      |         | indicate visibility
      |         | (PSR2.Methods.MethodDeclaration.Underscore)
 1255 | WARNING | Method name "_validate_tasks" should not be
      |         | prefixed with an underscore to indicate
      |         | visibility
      |         | (PSR2.Methods.MethodDeclaration.Underscore)
----------------------------------------------------------------------


FILE: ...lopment/themes/storefront/inc/nux/class-storefront-nux-admin.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 3 WARNINGS AFFECTING 3 LINES
----------------------------------------------------------------------
 272 | WARNING | Method name "_set_woocommerce_pages_full_width"
     |         | should not be prefixed with an underscore to
     |         | indicate visibility
     |         | (PSR2.Methods.MethodDeclaration.Underscore)
 288 | WARNING | Method name "_assign_page_template" should not be
     |         | prefixed with an underscore to indicate
     |         | visibility
     |         | (PSR2.Methods.MethodDeclaration.Underscore)
 302 | WARNING | Method name "_is_woocommerce_empty" should not be
     |         | prefixed with an underscore to indicate
     |         | visibility
     |         | (PSR2.Methods.MethodDeclaration.Underscore)
----------------------------------------------------------------------

Time: 10.15 secs; Memory: 32MB

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! storefront@2.6.0 lint:php: `composer run-script phpcs ./`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the storefront@2.6.0 lint:php script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nielslange/.npm/_logs/2020-09-19T09_19_48_984Z-debug.log
```

Fixing `(PHPCompatibility.ParameterValues.RemovedImplodeFlScript phpcs --extensions=php -s -p handling the phpcs event returned with error code 1 exibleParamOrder.Deprecated)` results in another exit due an error code. Fixing that one, results yet in another exit, and so on. I'm ready to going down the rabbit hole to eliminate all warnings and ensure that `npm run lint:php` will not be exited early.

### PR DESCRIPTION
**Pull request by nielslange**
Fixes #1473

Fix PHP linting warnings `PSR2.Methods.MethodDeclaration.Underscore` and `WordPress.WhiteSpace.PrecisionAlignment.Found` as discussed in https://github.com/woocommerce/storefront/pull/1474#issuecomment-700367646

I just pushed the PR again and I'm no longer facing a commit error as mentioned in https://github.com/woocommerce/storefront/pull/1474#issuecomment-703474227. Not sure what caused this error. I'll keep an eye on it.

### CODE REVIEW

File: inc/nux/class-storefront-nux-starter-content.php [hunk 1]
```diff
@@ -354,14 +354,14 @@ public function wc_query( $query ) {
...
-			$existing_products = $this->_get_existing_wc_products();
+			$existing_products = $this->get_existing_wc_products();
 
 			if ( ! empty( $existing_products ) ) {
 				$post__in = array_merge( $post__in, $existing_products );
 			}
 
 			// Add starter content.
-			$created_products = $this->_get_created_starter_content_products();
+			$created_products = $this->get_createdstarter_content_products();
```
Comment (haszari) [inline inc/nux/class-storefront-nux-starter-content.php]: I see there's still a little typo / search-replace issue here – this should be `get_created_starter_content_products()`, right?

File: inc/nux/class-storefront-nux-starter-content.php [hunk 2]
```diff
@@ -656,7 +656,7 @@ public function filter_sf_categories( $args ) {
 				$args['hide_empty'] = false;
 
 				// List of categories to display.
-				$args['ids'] = implode( $product_cats, ',' );
+				$args['ids'] = implode( ',', $product_cats );
```
Comment (haszari) [inline inc/nux/class-storefront-nux-starter-content.php]: TIL that this function [will work with the arguments the wrong (deprecated) way around](https://www.php.net/manual/en/function.implode.php)!

File: inc/nux/class-storefront-nux-starter-content.php [hunk 3]
```diff
@@ -997,7 +997,7 @@ private function _starter_content_products() {
 				$products[ $symbol ]['post_name'] = $symbol;
 			}
 
-			return apply_filters( 'storefront_starter_content_products', $products );
+			return apply_filters( 'storefrontstarter_content_products', $products );
```
Comment (haszari) [inline inc/nux/class-storefront-nux-starter-content.php]: We can't change the name of this filter without good reason - this will break any sites that implement the filter.

**Review by haszari — COMMENTED** [review]
Thanks for tackling these low-hanging fruit Niels!

I've added some inline comments - there are a couple of blockers here before we merge. 

- We shouldn't change the `storefront_starter_content_products` filter hook name. 
- `get_created_starter_content_products()` name should use consistent `_` between all words. This doesn't actually cause any damage/problems but let's not introduce a non-conventional function name in this PR.

The other thing to be explicit about in this PR is what [flows/features are touched by this change](https://github.com/woocommerce/storefront/wiki/Testing-Storefront:-flows-and-features). Since Storefront has such a huge user base, we need to take care with every code change, even simple refactoring and renaming. 

Can you please review the changes, determine what features are powered by the changed code, and then note that potential impact in the PR description? This helps with the following:

- It's an opportunity for you to document how you've tested this PR, so reviewers can optimise any additional testing time, or catch any unexpected gaps.
- Any possible impact is highlighted early and clearly for Storefront users. 

This level of care helps us to get the most out of the RC testing period as we're all fully aware of what parts of the product have been touched by the recent PRs.  

Thanks for your help making Storefront a safe upgrade for our merchants!

File: inc/nux/class-storefront-nux-starter-content.php (hunk 2 above)
Comment (nielslange) [reply inc/nux/class-storefront-nux-starter-content.php]: It does work, but does that justify running deprecated code? 🤔

File: inc/nux/class-storefront-nux-starter-content.php (hunk 1 above)
Comment (nielslange) [reply inc/nux/class-storefront-nux-starter-content.php]: Yes, `get_createdstarter_content_products()` is definitely wrong. Not sure what happened in this case, but somehow, I broke it and just fixed it.

File: inc/nux/class-storefront-nux-starter-content.php (hunk 3 above)
Comment (nielslange) [reply inc/nux/class-storefront-nux-starter-content.php]: Similar to the other case, I cannot explain what happened here. Of course, changing the name of a filter does not make any sense. Not sure if this change got triggered by linting or something else. It was definitely not consciously and I would have removed it from the push if I had caught it. That said, I also reverted this change and pushed an updated version.

File: inc/nux/class-storefront-nux-starter-content.php (hunk 2 above)
Comment (haszari) [reply inc/nux/class-storefront-nux-starter-content.php]: Of course not, we definitely want the arguments in a non-deprecated order!

Comment (nielslange) [reply inc/nux/class-storefront-nux-starter-content.php]: Than we can mark this part as resolved, right?

Comment (haszari) [reply inc/nux/class-storefront-nux-starter-content.php]: For sure, I totally approve of this change, was just commenting 😄

**Review by Aljullu — COMMENTED** [review]
Nice to see PHP linting changes being fixed, thanks @nielslange!

I reviewed the changes and they look good to me, everything seems quite safe too. However, I agree with @haszari that it would be good to have some testing steps to ensure we didn't introduce any regressions. Looking at the code, it seems that most changes affect the onboarding steps/banner and the notice to install WC if it's not installed. Can you confirm @nielslange? If that's the case, adding testing steps in order to go through those processes to ensure there isn't anything broken would be enough IMO.

**Comment by mikejolley** [comment]
@Aljullu @nielslange A long time ago `_` prefixes were used to indicate that a method was private (in PHP 4 compatible way I think) — I'm not sure why that pattern was adopted here, but since we are renaming methods any way (`_is_plugin_installed ` to `is_plugin_installed `) perhaps now would be a good time to change them to private?

**Review by mikejolley — APPROVED** [review]
@Aljullu I've made some small changes and made that method private — would you mind giving this a review also?

**Review by Aljullu — APPROVED** [review]
Changes look good. I made also some basic smoke testing and couldn't spot anything off. LGTM :ship:
