### PR TITLE
Customizer: Adjust footer heading and link color

### LINKED ISSUE #1260: Customizer Footer Heading & Link colors not applying
When inserting a widget in a footer column, the title of that widget does not change when you customize the footer header color

## To Reproduce
1. Go to Widgets
2. Add a widget in the footer area

image

3. Go to the customization page and try to change the title color

image

In `storefront/inc/customizer/class-storefront-customizer.php:793` we have the following:

```
.site-footer h1, .site-footer h2, .site-footer h3, .site-footer h4, .site-footer h5, .site-footer h6 {
    color: ' . $storefront_theme_mods['footer_heading_color'] . ';
}
```

And in `storefront/inc/class-storefront.php:280`:

```
$widget_tags = array(
    'before_widget' => '<div id="%1$s" class="widget %2$s">',
    'after_widget'  => '</div>',
    'before_title'  => '<span class="gamma widget-title">',
    'after_title'   => '</span>',
);
```

Solution: add `.site-footer .widget-title` in `storefront/inc/customizer/class-storefront-customizer.php:793`

I consider it a theme bug, because to fix this, it would be necessary to change the tag via filter

### PR DESCRIPTION
**Pull request by nielslange**
Fixes #1260 

**Before:**

#1260-before

**After:**

#1260-after

Note: The wired colour scheme had been selected for demonstration purposes. 😁

### CODE REVIEW

**Comment by haszari** [comment]
@senadir can you give this another test & review please? Feel free to merge when you're happy :)

File: inc/customizer/class-storefront-customizer.php [hunk 1]
```diff
@@ -786,11 +786,12 @@ public function get_css() {
 				color: ' . $storefront_theme_mods['footer_text_color'] . ';
 			}
 
-			.site-footer a:not(.button) {
+			.site-footer a:not(.button),
```
Comment (Aljullu) [inline inc/customizer/class-storefront-customizer.php]: It should be safe to remove this line now, the next one has more specificity and we don't want to change the color of button components anyway (elements with the `.components-button` class).
```suggestion
```

File: inc/customizer/class-storefront-customizer.php [hunk 2]
```diff
@@ -786,11 +786,12 @@ public function get_css() {
...
+			.site-footer a:not(.button):not(.components-button) {
 				color: ' . $storefront_theme_mods['footer_link_color'] . ';
 			}
 
-			.site-footer h1, .site-footer h2, .site-footer h3, .site-footer h4, .site-footer h5, .site-footer h6 {
+			.site-footer h1, .site-footer h2, .site-footer h3, .site-footer h4, .site-footer h5, .site-footer h6, .widget .widget-title, .widget .widgettitle {
```
Comment (Aljullu) [inline inc/customizer/class-storefront-customizer.php]: These two new classes should be prepended with the `.site-footer` selector, no?
```suggestion
			.site-footer h1, .site-footer h2, .site-footer h3, .site-footer h4, .site-footer h5, .site-footer h6, .site-footer .widget .widget-title, .site-footer .widget .widgettitle {
```
Otherwise it's being applied to sidebar widgets as well:
imatge

File: inc/customizer/class-storefront-customizer.php (hunk 1 above)
Comment (nielslange) [reply inc/customizer/class-storefront-customizer.php]: Thanks, @senadir, for adjusting this in https://github.com/woocommerce/storefront/pull/1261/commits/001c3a4324966e32437eb0c7d499f9bf874f3cd5 😉
